namespace TleReportingDashboard.Web.Services;

public class EmailService : IEmailService
{
    private const string SubjectPrefix = "[Automated Report] ";

    private const string MandatoryFooter =
        "<hr/><p style=\"font-size:11px;color:#888;\">This is an automated report generated by the Executive Reporting Suite. " +
        "Do not forward this email as it may contain sensitive loan data subject to regulatory requirements.</p>";

    private readonly ILogger<EmailService> _logger;

    public EmailService(ILogger<EmailService> logger)
    {
        _logger = logger;
    }

    public Task SendReportEmailAsync(string recipientEmail, string subject, string htmlBody,
        byte[]? attachment, string attachmentFileName)
    {
        var fullSubject = subject.StartsWith(SubjectPrefix, StringComparison.Ordinal)
            ? subject
            : SubjectPrefix + subject;

        var fullBody = htmlBody + MandatoryFooter;

        _logger.LogInformation(
            "Email send requested — To: {Recipient}, Subject: {Subject}, " +
            "HasAttachment: {HasAttachment}, AttachmentName: {AttachmentName}, BodyLength: {BodyLength}",
            recipientEmail, fullSubject, attachment is not null, attachmentFileName, fullBody.Length);

        // Stub: real Microsoft Graph implementation will replace this.
        _logger.LogWarning("EmailService is running in stub mode. No email was actually sent to {Recipient}.", recipientEmail);

        return Task.CompletedTask;
    }
}
