using System.Text;

namespace TleReportingDashboard.Web.Services;

// Stub email service that drops the message + attachment to disk as a
// .eml file (RFC 822 / multipart MIME) instead of actually sending. Used
// for testing scheduled-report runs without an SMTP / Graph backend
// configured. Outlook opens .eml files natively on Windows — admins
// double-click the file in C:\Temp\Reporting to inspect the rendered
// email exactly as it would have been delivered.
//
// Replace this with the real Graph / SMTP implementation once available;
// the IEmailService contract stays the same so callers don't change.
public class EmailService : IEmailService
{
    private const string SubjectPrefix = "[Automated Report] ";
    // Default drop folder. Overridable via Email:DropFolder in appsettings
    // so tests can redirect to a different path without recompiling.
    private const string DefaultDropFolder = @"C:\Temp\Reporting";
    // From address used in the .eml's "From:" header. Real SMTP would
    // pick this up from Smtp:FromAddress; for the file drop it's just
    // a label so Outlook has something to render.
    private const string FromAddress = "noreply@ralisservices.com";
    private const string FromDisplayName = "Executive Reporting Suite";

    private const string MandatoryFooter =
        "<hr/><p style=\"font-size:11px;color:#888;\">This is an automated report generated by the Executive Reporting Suite. " +
        "Do not forward this email as it may contain sensitive loan data subject to regulatory requirements.</p>";

    private readonly ILogger<EmailService> _logger;
    private readonly string _dropFolder;

    public EmailService(IConfiguration configuration, ILogger<EmailService> logger)
    {
        _logger = logger;
        _dropFolder = configuration["Email:DropFolder"] ?? DefaultDropFolder;
    }

    public async Task SendReportEmailAsync(string recipientEmail, string subject, string htmlBody,
        byte[]? attachment, string attachmentFileName)
    {
        var fullSubject = subject.StartsWith(SubjectPrefix, StringComparison.Ordinal)
            ? subject
            : SubjectPrefix + subject;

        var fullBody = htmlBody + MandatoryFooter;

        try
        {
            Directory.CreateDirectory(_dropFolder);
            var filePath = BuildDropPath(_dropFolder, recipientEmail, fullSubject);
            var emlBytes = BuildEml(recipientEmail, fullSubject, fullBody, attachment, attachmentFileName);
            await File.WriteAllBytesAsync(filePath, emlBytes);

            _logger.LogInformation(
                "Email written as .eml to {Path} — To: {Recipient}, Subject: {Subject}, " +
                "HasAttachment: {HasAttachment}, AttachmentName: {AttachmentName}",
                filePath, recipientEmail, fullSubject, attachment is not null, attachmentFileName);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex,
                "Failed to write email .eml file for {Recipient} (subject: {Subject})",
                recipientEmail, fullSubject);
            throw;
        }
    }

    // Generates a deterministic, FS-safe filename: timestamp_recipient_subject.eml.
    // Timestamp first so the directory listing sorts chronologically; admins
    // looking for "the last failed run" just sort by name and grab the bottom.
    private static string BuildDropPath(string folder, string recipient, string subject)
    {
        var timestamp = DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");
        var safeRecipient = SanitizeForFileName(recipient, 64);
        var safeSubject = SanitizeForFileName(subject, 80);
        var fileName = $"{timestamp}_{safeRecipient}_{safeSubject}.eml";
        return Path.Combine(folder, fileName);
    }

    private static string SanitizeForFileName(string value, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value)) return "unnamed";
        var invalid = Path.GetInvalidFileNameChars();
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(invalid.Contains(ch) ? '_' : ch);
        }
        var result = sb.ToString().Trim();
        return result.Length > maxLength ? result[..maxLength] : result;
    }

    // Hand-rolled MIME multipart/mixed serializer. No NuGet dep on
    // MimeKit/MailKit — the format is small enough to write directly,
    // and this code is meant to be deleted when the real implementation
    // lands. Headers + text/html body + optional binary attachment.
    private static byte[] BuildEml(
        string recipient, string subject, string htmlBody,
        byte[]? attachment, string attachmentFileName)
    {
        var boundary = "----=_NextPart_" + Guid.NewGuid().ToString("N");
        var sb = new StringBuilder();

        // Headers. RFC 822 uses CRLF line endings everywhere — Outlook
        // tolerates LF on Windows but Apple Mail and some web clients
        // refuse to parse without proper CRLFs, so we're explicit.
        sb.Append("From: ").Append(FromDisplayName).Append(" <").Append(FromAddress).Append(">\r\n");
        sb.Append("To: ").Append(recipient).Append("\r\n");
        sb.Append("Subject: ").Append(EncodeHeader(subject)).Append("\r\n");
        sb.Append("Date: ").Append(DateTime.UtcNow.ToString("ddd, dd MMM yyyy HH:mm:ss")).Append(" +0000\r\n");
        sb.Append("MIME-Version: 1.0\r\n");

        if (attachment is null || attachment.Length == 0)
        {
            // Single-part message — body only.
            sb.Append("Content-Type: text/html; charset=utf-8\r\n");
            sb.Append("Content-Transfer-Encoding: base64\r\n");
            sb.Append("\r\n");
            sb.Append(EncodeBase64Wrapped(Encoding.UTF8.GetBytes(htmlBody)));
        }
        else
        {
            // Multipart: HTML body + one attachment.
            sb.Append("Content-Type: multipart/mixed; boundary=\"").Append(boundary).Append("\"\r\n");
            sb.Append("\r\n");
            sb.Append("This is a multi-part message in MIME format.\r\n\r\n");

            // Body part
            sb.Append("--").Append(boundary).Append("\r\n");
            sb.Append("Content-Type: text/html; charset=utf-8\r\n");
            sb.Append("Content-Transfer-Encoding: base64\r\n");
            sb.Append("\r\n");
            sb.Append(EncodeBase64Wrapped(Encoding.UTF8.GetBytes(htmlBody)));
            sb.Append("\r\n");

            // Attachment part
            sb.Append("--").Append(boundary).Append("\r\n");
            sb.Append("Content-Type: ").Append(GuessMimeType(attachmentFileName))
              .Append("; name=\"").Append(attachmentFileName).Append("\"\r\n");
            sb.Append("Content-Transfer-Encoding: base64\r\n");
            sb.Append("Content-Disposition: attachment; filename=\"").Append(attachmentFileName).Append("\"\r\n");
            sb.Append("\r\n");
            sb.Append(EncodeBase64Wrapped(attachment));
            sb.Append("\r\n");

            // Closing boundary (note the trailing -- per RFC 2046).
            sb.Append("--").Append(boundary).Append("--\r\n");
        }

        return Encoding.UTF8.GetBytes(sb.ToString());
    }

    // Encodes a non-ASCII subject line via RFC 2047 encoded-word syntax
    // when it contains characters Outlook would otherwise mangle. Pure-
    // ASCII subjects pass through unchanged so the .eml stays readable
    // when opened in a text editor.
    private static string EncodeHeader(string value)
    {
        if (value.All(c => c < 128 && c >= 32))
            return value;
        var b64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(value));
        return $"=?utf-8?B?{b64}?=";
    }

    // RFC 2045 requires base64 lines no longer than 76 chars. Real mail
    // servers reject (or mangle) longer lines silently, so we wrap.
    private static string EncodeBase64Wrapped(byte[] data)
    {
        var b64 = Convert.ToBase64String(data);
        var sb = new StringBuilder(b64.Length + (b64.Length / 76 * 2));
        for (var i = 0; i < b64.Length; i += 76)
        {
            var chunk = Math.Min(76, b64.Length - i);
            sb.Append(b64, i, chunk).Append("\r\n");
        }
        return sb.ToString();
    }

    private static string GuessMimeType(string fileName)
    {
        var ext = Path.GetExtension(fileName).ToLowerInvariant();
        return ext switch
        {
            ".xlsx" => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ".xls"  => "application/vnd.ms-excel",
            ".csv"  => "text/csv",
            ".pdf"  => "application/pdf",
            ".txt"  => "text/plain",
            _       => "application/octet-stream"
        };
    }
}
